name: Build and Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java_version: [8, 11, 17, 18, 19, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd openjdk-${{ matrix.java_version }}
          
          # Build the Docker image with the appropriate tag
          docker buildx create --use
          docker build . --tag ghcr.io/david1117dev/docker-test:${{ matrix.java_version }}
          docker push ghcr.io/david1117dev/docker-test:${{ matrix.java_version }}
